/**
 * ESP32 secrets file
 * 
 * Contains information required to connect to WiFi and in-turn, AWS IoT
 * 
 * Authors: Vipul Deshpande, Jaime Burbano
 */


/*
  Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
  Permission is hereby granted, free of charge, to any person obtaining a copy of this
  software and associated documentation files (the "Software"), to deal in the Software
  without restriction, including without limitation the rights to use, copy, modify,
  merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
  permit persons to whom the Software is furnished to do so.
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
  INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
  PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
  HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
  OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/


#include <pgmspace.h>

#define SECRET
#define THINGNAME "SubscriberG01"

const char WIFI_SSID[] = "Samsung4G";
const char WIFI_PASSWORD[] = "qqwweerr";
const char AWS_IOT_ENDPOINT[] = "atihyecguq1md-ats.iot.eu-central-1.amazonaws.com";

/* Amazon Root CA 1 */
static const char AWS_CERT_CA[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF
ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6
b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL
MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv
b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj
ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM
9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw
IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6
VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L
93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm
jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC
AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA
A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI
U5PMCCjjmCXPI6T53iHTfIUJrU6adTrCC2qJeHZERxhlbI1Bjjt/msv0tadQ1wUs
N+gDS63pYaACbvXy8MWy7Vu33PqUXHeeE6V/Uq2V8viTO96LXFvKWlJbYK8U90vv
o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU
5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy
rqXRfboQnoZsG4q5WTP468SQvvG5
-----END CERTIFICATE-----
)EOF";

/* Device Certificate */
static const char AWS_CERT_CRT[] PROGMEM = R"KEY(
-----BEGIN CERTIFICATE-----
MIIDWjCCAkKgAwIBAgIVANWoQDjcLJ9SnVuauSdrPf43ghGGMA0GCSqGSIb3DQEB
CwUAME0xSzBJBgNVBAsMQkFtYXpvbiBXZWIgU2VydmljZXMgTz1BbWF6b24uY29t
IEluYy4gTD1TZWF0dGxlIFNUPVdhc2hpbmd0b24gQz1VUzAeFw0yMzEyMjMxMzEy
MTlaFw00OTEyMzEyMzU5NTlaMB4xHDAaBgNVBAMME0FXUyBJb1QgQ2VydGlmaWNh
dGUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDaSucQ8OW08/hmRggb
95r9rlVlePozgJ7XCatk73FEG0GCCQojy+697095coweYy/QOkPt4FZBSWPKLSbg
5aFxxJUm1PujWTlaaahzf4YVvJFkX4sK44mOwA1efq3wI5qC0aoY9RE85b76KWlE
2oF13pDbfee/XuAZVxv3EI5R/uEFRZvqXrJ+MSSn3/9glMDyHpECDvjf0Xwjl3RK
QSylKb8Pn8nt17OhfWMWEeIyYEOYtNgM8ha+mKpbHgvKbHxTIQqN7hX+2qEMNUU1
u5sA0k2xN/aIbmH3upBBST7nTlGcoSXBaQFm1+XYJevjrubKpbyAitL92bBtnemf
xMqzAgMBAAGjYDBeMB8GA1UdIwQYMBaAFJ1EfVKG4l07hvlaFGA+o1EK+K0wMB0G
A1UdDgQWBBR6nkZoxw6bBNY2unIspWq89jxyXjAMBgNVHRMBAf8EAjAAMA4GA1Ud
DwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAQEANYy+u+Gma3nFSds6tPkH5vy1
RreQOzo9Q2nTlVGWUIcw5SURwKArBde9tQFa9aS2UXkAmgAGbVb/rvZfw2mTZ81z
kdaX4Ay6E9o8dncRioz1s7s+KVPDWC7oJJ5gIQ8A4NUq4RJDWfpjcgv6XGnC1fPY
pM6+25I3ZoFCKzInsglcx/VoWtuese2isU+qxWgO8srwxWMdyWmifZ4eiPcrwjc/
CKG5Zx6vjBbNldA2wna27nK/ug9sHGmefseDJEMJ94ADbEAKlLDXViDHdRj1jmKs
2nQfI9Jw70B5ZpQH8NFQlFt9OwDVVmWT8y8bmkZoBh3V2TG1wv37tqqHGT9i6g==
-----END CERTIFICATE-----
)KEY";

/* Device Private Key */
static const char AWS_CERT_PRIVATE[] PROGMEM = R"KEY(
-----BEGIN RSA PRIVATE KEY-----
MIIEogIBAAKCAQEA2krnEPDltPP4ZkYIG/ea/a5VZXj6M4Ce1wmrZO9xRBtBggkK
I8vuve9PeXKMHmMv0DpD7eBWQUljyi0m4OWhccSVJtT7o1k5Wmmoc3+GFbyRZF+L
CuOJjsANXn6t8COagtGqGPURPOW++ilpRNqBdd6Q233nv17gGVcb9xCOUf7hBUWb
6l6yfjEkp9//YJTA8h6RAg7439F8I5d0SkEspSm/D5/J7dezoX1jFhHiMmBDmLTY
DPIWvpiqWx4Lymx8UyEKje4V/tqhDDVFNbubANJNsTf2iG5h97qQQUk+505RnKEl
wWkBZtfl2CXr467myqW8gIrS/dmwbZ3pn8TKswIDAQABAoIBAFV+6KkV8KHCvBMy
cpKhk66vzPqFO1lYkt2eB+bscOw/0JRhffsvMD5rsDDc0ExGhL+FUn2kU6QWXmMc
9BE5XtX0LIac/EGp/HCQ2U0DMTzqMfeiBA8rtwCV76aG7xESoL2D6J8FvM6hHP9V
oMk622GS3iFZWp71Rcgm+ej2LwellrzDuxH/hIRHZRdVd4q2/AkmqKeVBr1PwHZt
ta/qozBPwYGsHTupljUW7cLwoSrAraleyRYMWPIBviByS11n1Q8fhPhTQRQQJpu2
Ne3GliJeU+C9v2EsQFkqqr5DIxosHGux5ZNjyfecTRMvdf0rXpbR2LSxL/Z0phGu
jbk3egECgYEA8XyibbVCxIShw26j7ideg/Q+uFASG5/pVge//lRIC5tAVHy+2PGx
cK4j8WTJilA0QnuHadpeIZ7g4FN+tjjRphKC8PI7rekUwoYXmdD+kSUp6gBqQwoF
tcPCauJV4ZFTSqsazf2dbDW1EGvz716Nkjzv+L8UDOeNNDyIEG0srvMCgYEA52lq
abZM0Ij64WpwOFFcydD3fFF3oorNj85ius089TSmGNEOq7ssgZjwLNtOmwgDTu1C
oSx/8NTuAPte6EMZ9GIAzAQOtRZb7IcvU4HQ6BkhPvUgM2eiEKRcUh9rq9/IS8M5
fodsBeYIasBJWkPFLW+BghrOxgLI1F/LiCKf5UECgYB+vniN9i3V8PrqFP7rNzSP
MzlcCYKHhzWzlpu5Q8kQdmqcLWEJgkksJ+nrf4ecFZ5oKmeXMipnoPjMJGaEA2xd
qqeZCLoz+/qOYkyuyZdi3MuT6qXbC76VeOpoqOSEYH8D2KxX4z2llsaymMZOIyVQ
1LTqrHc8kqd0/DQ50uM56wKBgDMZzC3b28qQ9RWh83X8QYkvY/dH5is2i34eDR9D
AxsCrUr9n0e85W8Y3rCJHSqO8mwTaIs+0GHWI1iEKckQSEL3AUYL/1NtxI7Oq1y9
Zexa4ESOzLWNRPR31wsrdRNXL1vLmH6gWPJUgbdRDuGn5XrLDMY2NUL0inSbUs6V
FsoBAoGAOyp+lMmnXgXea9U6fisiNroDOSccBR569F//jEhC5gYP7JP6XO1+xmA1
TcgjjZKf/VZu2LBeNUFhfaSdLkYY5aRbzDfzjVUrVYJ/T7Enevwj45fORcktMWGJ
tHC4QDhhmX24fwSMobPRbov1Y9FagEkju0IMaoZeQ/9imBD5vCk=
-----END RSA PRIVATE KEY-----
)KEY";